In [2]:
import pandas as pd
import json

In [3]:
SEASON = 2025

In [4]:
df = pd.read_csv('my_submission.csv')

df.head()

   RowId Tournament  Bracket  Slot  Team
0      0          M        1   W16  W16a
1      1          M        1   X11  X11b
2      2          M        1   Y11  Y11a
3      3          M        1   Y16  Y16a
4      4          M        1  R1W1   W01

In [28]:
teams_df = pd.read_csv('input/march-machine-learning-mania-2024/MTeams.csv')
seeds_df = pd.read_csv('input/march-machine-learning-mania-2024/2024_tourney_seeds.csv')

with open(f'{SEASON}_win_probability_matrix.json', 'r') as json_file:
    win_probability_matrix = json.load(json_file)

In [29]:
unique_slots = df['Slot'].unique()
slots = unique_slots

num_simulations = len(df['Bracket'].unique())

In [67]:
test_df = df[df['Bracket'] <= 10]

# def concat_slot_team(group):
#     # Concatenate 'Slot' and 'Team' for each row, then join all for the group
#     return ' '.join(group['Slot'] + '_' + group['Team'])


# compressed_df = df.groupby('Bracket').apply(concat_slot_team)

# display(compressed_df)

In [71]:
groups = df[df['Bracket'] <= 3].groupby('Bracket')
for bracket, bracket_df in groups:
    print(bracket)
    display(bracket_df)

1

    RowId Tournament  Bracket  Slot Team
0       0          M        1  R1W1  W01
1       1          M        1  R1W2  W02
2       2          M        1  R1W3  W03
3       3          M        1  R1W4  W04
4       4          M        1  R1W5  W05
..    ...        ...      ...   ...  ...
58     58          M        1  R4Y1  Y01
59     59          M        1  R4Z1  Z04
60     60          M        1  R5WX  X02
61     61          M        1  R5YZ  Y01
62     62          M        1  R6CH  Y01

[63 rows x 5 columns]

2

     RowId Tournament  Bracket  Slot Team
63      63          M        2  R1W1  W01
64      64          M        2  R1W2  W15
65      65          M        2  R1W3  W03
66      66          M        2  R1W4  W04
67      67          M        2  R1W5  W05
..     ...        ...      ...   ...  ...
121    121          M        2  R4Y1  Y01
122    122          M        2  R4Z1  Z01
123    123          M        2  R5WX  X04
124    124          M        2  R5YZ  Z01
125    125          M        2  R6CH  X04

[63 rows x 5 columns]

3

     RowId Tournament  Bracket  Slot Team
126    126          M        3  R1W1  W01
127    127          M        3  R1W2  W02
128    128          M        3  R1W3  W14
129    129          M        3  R1W4  W04
130    130          M        3  R1W5  W05
..     ...        ...      ...   ...  ...
184    184          M        3  R4Y1  Y01
185    185          M        3  R4Z1  Z03
186    186          M        3  R5WX  W01
187    187          M        3  R5YZ  Z03
188    188          M        3  R6CH  Z03

[63 rows x 5 columns]

In [63]:
value_counts = compressed_df.value_counts()
duplicates = value_counts[value_counts > 1]
print(duplicates.head(5))
print(duplicates.empty)

Series([], Name: count, dtype: int64)
True

In [31]:
print(bracket_sets.iloc[0])

{('R1X5', 'X05'), ('R3Y2', 'Y06'), ('R1Y8', 'Y08'), ('R1Z5', 'Z12'), ('R1Y1', 'Y01'), ('R5YZ', 'Y01'), ('R2X4', 'X04'), ('R2Z3', 'Z06'), ('R1Z3', 'Z03'), ('R1W1', 'W01'), ('R1Y7', 'Y07'), ('R2Y1', 'Y01'), ('R1Z4', 'Z04'), ('R1X6', 'X06'), ('R1Z7', 'Z10'), ('R2W1', 'W01'), ('R1Y4', 'Y13'), ('R2Z2', 'Z02'), ('R1Y3', 'Y03'), ('R2Z4', 'Z04'), ('R1Z1', 'Z01'), ('R2W3', 'W06'), ('R1X4', 'X04'), ('R1X7', 'X07'), ('R1Z6', 'Z06'), ('R2W4', 'W04'), ('R2X1', 'X08'), ('R3Z2', 'Z02'), ('R1Y2', 'Y02'), ('R2Y4', 'Y05'), ('R4W1', 'W02'), ('R1Z8', 'Z08'), ('R1X2', 'X02'), ('R2X3', 'X03'), ('R1W7', 'W07'), ('R3Y1', 'Y01'), ('R1X8', 'X08'), ('R1W6', 'W06'), ('R1W5', 'W05'), ('R1Y5', 'Y05'), ('R4Z1', 'Z04'), ('R4Y1', 'Y01'), ('R1Y6', 'Y06'), ('R1X1', 'X01'), ('R1Z2', 'Z02'), ('R1W2', 'W02'), ('R2X2', 'X02'), ('R1W4', 'W04'), ('R1X3', 'X03'), ('R3W1', 'W01'), ('R3Z1', 'Z04'), ('R3X2', 'X02'), ('R3X1', 'X04'), ('R2Y2', 'Y02'), ('R2W2', 'W02'), ('R3W2', 'W02'), ('R4X1', 'X02'), ('R6CH', 'Y01'), ('R5WX', 'X02'), ('R1W8', 'W08'), ('R2Z1', 'Z08'), ('R2Y3', 'Y06'), ('R1W3', 'W03')}

In [15]:
slots = ['R4W1', 'R4X1', 'R4Y1', 'R4Z1', 'R5WX', 'R5YZ', 'R6CH']
for slot in slots:
    filtered_df = df[(df['Slot'] == slot) & (df['Tournament'] == 'M')]
    seed_counts = filtered_df['Team'].value_counts()
    print("Most occurrences for slot {}".format(slot))
    for (seed, occurrences) in seed_counts.head(4).items():
        seed_df = seeds_df[(seeds_df['Seed'] == seed) & (seeds_df['Tournament'] == 'M')]
        if len(seed_df) > 1:
            print("seed_df contains more than one row")
        else:
            team_id = seed_df.iloc[0]['TeamID']
            team_name = teams_df[teams_df['TeamID'] == team_id].iloc[0]['TeamName']
            print(f"{team_name} wins {occurrences/num_simulations * 100:.2f}% of the time")
    print("")

Most occurrences for slot R4W1
Connecticut wins 35.27% of the time
Iowa St wins 16.18% of the time
Auburn wins 15.62% of the time
Illinois wins 12.69% of the time

Most occurrences for slot R4X1
Arizona wins 27.01% of the time
Alabama wins 18.21% of the time
North Carolina wins 15.77% of the time
Baylor wins 13.97% of the time

Most occurrences for slot R4Y1
Purdue wins 38.41% of the time
Tennessee wins 21.37% of the time
Creighton wins 12.96% of the time
Kansas wins 8.43% of the time

Most occurrences for slot R4Z1
Houston wins 41.17% of the time
Marquette wins 16.52% of the time
Duke wins 15.08% of the time
Kentucky wins 9.29% of the time

Most occurrences for slot R5WX
Connecticut wins 22.80% of the time
Arizona wins 14.71% of the time
Alabama wins 9.13% of the time
Auburn wins 8.32% of the time

Most occurrences for slot R5YZ
Houston wins 25.61% of the time
Purdue wins 23.20% of the time
Tennessee wins 11.23% of the time
Marquette wins 7.63% of the time

Most occurrences for slot R6CH
Houston wins 16.45% of the time
Purdue wins 14.16% of the time
Connecticut wins 12.97% of the time
Arizona wins 7.57% of the time