In [70]:
import pandas as pd
import os
from itertools import chain
import glob
import fnmatch
import numpy as np
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from enum import Enum
from datetime import datetime
import requests
from bs4 import BeautifulSoup
import json

In [73]:
class LabelType(Enum):
    MARGIN_OF_VICTORY = "mov"
    WIN_PROBABILITY = "win_probability"

class TournamentDivision(Enum):
    MEN = "M"
    WOMEN = "W"

In [ ]:
SEASON = 2026
DIVISION = TournamentDivision.MEN
LABEL_TYPE = LabelType.WIN_PROBABILITY
REFRESH_KENPOM = False
EPOCHS = 100

# Data collection

In [30]:
DATA_DIRS = [f'march-machine-learning-mania-{SEASON}', '../kenpom']

CSV = {}
for path in list(chain(*map(lambda x: glob.glob(x + '/*.csv'), DATA_DIRS))):
    CSV[os.path.basename(path).split('.')[0]] = pd.read_csv(path, encoding='cp1252')
print(CSV.keys())

dict_keys(['MNCAATourneyDetailedResults', 'SampleSubmissionStage2', 'WSecondaryTourneyTeams', 'WNCAATourneySlots', 'MNCAATourneyCompactResults', 'MSeasons', 'SampleSubmissionStage1', 'WTeams', 'MRegularSeasonDetailedResults', 'WNCAATourneyDetailedResults', 'MNCAATourneySlots', 'MGameCities', 'MConferenceTourneyGames', 'WNCAATourneyCompactResults', 'WSecondaryTourneyCompactResults', 'WSeasons', 'Cities', 'WRegularSeasonCompactResults', 'WTeamSpellings', 'WRegularSeasonDetailedResults', 'MRegularSeasonCompactResults', 'WNCAATourneySeeds', 'MNCAATourneySeedRoundSlots', 'WConferenceTourneyGames', 'WTeamConferences', 'MTeamConferences', 'MTeamCoaches', 'MMasseyOrdinals', 'Conferences', 'MTeams', 'WGameCities', 'MNCAATourneySeeds', 'MSecondaryTourneyTeams', 'MTeamSpellings', 'SeedBenchmarkStage1', 'MSecondaryTourneyCompactResults', 'kenpom_2011-2024', 'kenpom_2025-03-19', 'kenpom_2025'])

In [31]:
manual_team_additions = [
    ('Alabama A&M;', 1105),
    ('Arkansas Little Rock', 1114),
    ('Arkansas Pine Bluff', 1115),
    ('Bethune Cookman', 1126),
    ('Cal St. Bakersfield', 1167),
    ('Dixie St.', 1469),
    ('Florida A&M;', 1197),
    ('Houston Christian', 1223),
    ('IUPU Fort Wayne', 1236),
    ('Illinois Chicago', 1227),
    ('LIU', 1254),
    ('Louisiana Lafayette', 1418),
    ('Louisiana Monroe', 1419),
    ('Louisiana St.', 1261),
    ('MD Baltimore County', 1420),
    ('Maryland Eastern Shore', 1271),
    ('Mississippi Valley St.', 1290),
    ('Missouri Kansas City', 1282),
    ('Nevada Las Vegas', 1424),
    ('NJ Inst of Technology', 1312),
    ('North Carolina A&T;', 1299),
    ('Prairie View A&M;', 1341),
    ('Queens', 1474),
    ('Saint Francis', 1384),
    ('Southeast Missouri St.', 1369),
    ('Southeast Missouri', 1369),
    ('St. Francis NY', 1383),
    ('St. Francis PA', 1384),
    ('St. Louis', 1387),
    ('Texas A&M Corpus Chris', 1394),
    ('St. Thomas', 1472),
    ('Tarleton St.', 1470),
    ('Tennessee Martin', 1404),
    ('Texas A&M;', 1401),
    ('Texas A&M; Commerce', 1477),
    ('Texas A&M; Corpus Chris', 1394),
    ('Texas El Paso', 1431),
    ('Texas Pan American', 1410),
    ('UT Rio Grande Valley', 1410),
    ('Virginia Military Inst', 1440),
    ('Wisconsin Green Bay', 1453),
    ('Wisconsin Milwaukee', 1454),
]
lower_manual_team_additions = [(team_name_spelling.lower(), team_id) for (team_name_spelling, team_id) in manual_team_additions]
manual_df = pd.DataFrame([{'TeamNameSpelling': tns, 'TeamID': tid} for (tns, tid) in lower_manual_team_additions])

mteam_spellings = CSV['MTeamSpellings']
mteam_spellings = pd.concat([mteam_spellings, manual_df], ignore_index=True)
# Remove duplicate team spellings while keeping the first occurrence
mteam_spellings = mteam_spellings.drop_duplicates(subset=['TeamNameSpelling'], keep='first')

teams_df = pd.merge(mteam_spellings, CSV['MTeams'], on='TeamID', how='inner').drop(['FirstD1Season', 'LastD1Season'], axis=1)
display(teams_df)

            TeamNameSpelling  TeamID        TeamName
0           a&m-corpus chris    1394  TAM C. Christi
1         a&m-corpus christi    1394  TAM C. Christi
2                abilene chr    1101     Abilene Chr
3          abilene christian    1101     Abilene Chr
4          abilene-christian    1101     Abilene Chr
...                      ...     ...             ...
1210      texas pan american    1410           UTRGV
1211    ut rio grande valley    1410           UTRGV
1212  virginia military inst    1440             VMI
1213     wisconsin green bay    1453    WI Green Bay
1214     wisconsin milwaukee    1454    WI Milwaukee

[1215 rows x 3 columns]

## Kenpom data
### (only for Men's, n/a for Women's)

In [32]:
# Scrape kenpom for most updated ratings in the current season
def parse_url(
    url,
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }
):  
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    return soup


# Headers in the correct order as found in the html table
column_definitions = [
    {"name": "Rk", "type": "int"},
    {"name": "Team", "type": "str"},
    {"name": "Conf", "type": "str"},
    {"name": "W-L", "type": "str"},
    {"name": "NetRtg", "type": "float"},
    {"name": "ORtg", "type": "float"},
    {"name": "seed_ORtg", "type": "int"},
    {"name": "DRtg", "type": "float"},
    {"name": "seed_DRtg", "type": "int"},
    {"name": "AdjT", "type": "float"},
    {"name": "seed_AdjT", "type": "int"},
    {"name": "Luck", "type": "float"},
    {"name": "seed_Luck", "type": "int"},
    {"name": "sos_NetRtg", "type": "float"},
    {"name": "seed_sos_NetRtg", "type": "int"},
    {"name": "sos_ORtg", "type": "float"},
    {"name": "seed_sos_ORtg", "type": "int"},
    {"name": "sos_DRtg", "type": "float"},
    {"name": "seed_sos_DRtg", "type": "int"},
    {"name": "ncsos_NetRtg", "type": "float"},
    {"name": "seed_ncsos_NetRtg", "type": "int"}
]

def extract_kenpom(soup, write_to_csv = False):
    # Find the table with rankings
    table = soup.find("table", {"id": "ratings-table"})
    assert table is not None, "Error: Ratings table not found!"
    
    # Extract team data
    teams = []
    
    for row in table.find("tbody").find_all("tr"):
        cols = row.find_all("td")
    
        # assert len(cols) == len(column_definitions), f"Error: Expected {len(column_definitions)} columns but found {len(cols)} in row: {row}"
    
        if (len(cols) == len(column_definitions)):
            row_data = []
            for i, col in enumerate(cols):
                text_value = col.text.strip()
    
                # Special handling for 'Team' column (avoid capturing seed numbers)
                if column_definitions[i]["name"] == "Team":
                    team_name = col.find("a").text.strip() if col.find("a") else col.text.strip()
                    row_data.append(team_name)
                else:
                    col_type = column_definitions[i]["type"]
                    if col_type == "int":
                        row_data.append(int(text_value))
                    elif col_type == "float":
                        row_data.append(float(text_value))
                    else:
                        row_data.append(text_value)  # Keep as string for other columns
        
            teams.append(row_data)
    
    # Convert to DataFrame
    refreshed_kenpom = pd.DataFrame(teams, columns=[col["name"] for col in column_definitions])

    if (write_to_csv):
        current_date = datetime.today().strftime('%Y-%m-%d')
        refreshed_kenpom.to_csv(f'../kenpom/kenpom_{current_date}.csv', index=False)

    return refreshed_kenpom

In [35]:
KENPOM_URL = "https://kenpom.com/"

if REFRESH_KENPOM:
    soup = parse_url(KENPOM_URL)
    refreshed_kenpom = extract_kenpom(soup, True)
else:
    # Find the most recent kenpom CSV file
    kenpom_files = sorted(
        [path for path in CSV.keys() if path.startswith("kenpom_")], 
        key=lambda x: x.split('_')[-1],  # Sort by the date in the filename
        reverse=True  # Most recent first
    )

    if kenpom_files:
        print(f'Not refreshing kenpom, using {kenpom_files[0]}')
        refreshed_kenpom = CSV[kenpom_files[0]]  # Load the most recent one
    else:
        refreshed_kenpom = None  # Handle case where no files are found


display(refreshed_kenpom)

Not refreshing kenpom, using kenpom_2025-03-19

,Rk,Team,Conf,W-L,NetRtg,ORtg,seed_ORtg,DRtg,seed_DRtg,AdjT,...,Luck,seed_Luck,sos_NetRtg,seed_sos_NetRtg,sos_ORtg,seed_sos_ORtg,sos_DRtg,seed_sos_DRtg,ncsos_NetRtg,seed_ncsos_NetRtg
0,1,Duke,ACC,31-3,38.27,128.0,3,89.7,4,65.7,...,-0.019,229,10.12,55,112.5,47,102.4,63,9.32,21
1,2,Florida,SEC,30-4,36.24,128.6,1,92.4,9,69.6,...,0.007,159,14.53,16,114.5,17,100.0,19,-1.96,231
2,3,Houston,B12,30-4,35.42,123.2,10,87.8,2,61.4,...,0.015,138,13.67,24,113.6,33,99.9,18,2.57,101
3,4,Auburn,SEC,28-5,35.16,128.5,2,93.3,12,67.6,...,0.030,100,19.11,2,117.1,2,98.0,1,10.40,19
4,5,Tennessee,SEC,27-7,31.20,120.3,18,89.1,3,63.6,...,0.016,135,16.02,6,116.7,4,100.6,32,-0.85,201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,360,Alabama A&M,SWAC,10-22,-23.50,92.0,361,115.5,334,71.0,...,-0.022,246,-9.70,359,101.1,352,110.8,357,1.86,120
360,361,Coppin St.,MEAC,6-24,-24.29,87.3,363,111.6,276,67.7,...,0.033,92,-4.31,279,105.3,244,109.6,302,4.32,64
361,362,Chicago St.,NEC,4-28,-24.38,91.8,362,116.2,341,68.2,...,-0.024,251,-3.30,247,104.3,286,107.6,184,8.49,29
362,363,Arkansas Pine Bluff,SWAC,6-25,-26.08,95.1,349,121.1,359,71.4,...,-0.074,342,-8.64,354,100.9,356,109.6,301,7.05,41
363,364,Mississippi Valley St.,SWAC,3-28,-42.23,82.6,364,124.8,364,64.8,...,-0.016,220,-3.51,256,103.8,294,107.3,171,18.50,2

In [37]:
# kenpom_2024.csv holds kenpom data from 2011-2024 - let's load all of that first
CSV['kenpom'] = CSV['kenpom_2011-2024']

# rename refreshed_kenpom columns to match kenpom_2011-2024.csv
refreshed_kenpom = refreshed_kenpom.rename(columns={
    'Team': 'TeamName',
    'ORtg': 'adj_o',
    'DRtg': 'adj_d',
    'AdjT': 'adj_tempo',
    'Luck': 'luck',
    'sos_ORtg': 'sos_adj_o',
    'sos_DRtg': 'sos_adj_d'
})
# Add the season column
refreshed_kenpom['Season'] = SEASON
# Reorder columns to match kenpom_2011-2024
refreshed_kenpom = refreshed_kenpom[['Season', 'TeamName', 'adj_o', 'adj_d', 'adj_tempo', 'luck', 'sos_adj_o', 'sos_adj_d']]
# Append SEASON data to CSV['kenpom']
CSV['kenpom'] = pd.concat([CSV['kenpom'], refreshed_kenpom], ignore_index=True)

display(CSV['kenpom'])

,Unnamed: 0,Season,TeamName,adj_o,adj_d,adj_tempo,luck,sos_adj_o,sos_adj_d
0,0.0,2011,Ohio St.,125.4,88.4,66.0,0.043,107.4,98.3
1,1.0,2011,Duke,118.8,87.2,70.1,0.006,106.0,97.4
2,2.0,2011,Kansas,119.8,88.3,69.6,0.071,106.1,98.7
3,3.0,2011,Texas,114.0,85.3,67.2,-0.055,105.6,97.8
4,4.0,2011,Purdue,116.1,87.2,67.1,-0.004,108.1,97.3
...,...,...,...,...,...,...,...,...,...
4944,NaN,2025,Alabama A&M,92.0,115.5,71.0,-0.022,101.1,110.8
4945,NaN,2025,Coppin St.,87.3,111.6,67.7,0.033,105.3,109.6
4946,NaN,2025,Chicago St.,91.8,116.2,68.2,-0.024,104.3,107.6
4947,NaN,2025,Arkansas Pine Bluff,95.1,121.1,71.4,-0.074,100.9,109.6
4948,NaN,2025,Mississippi Valley St.,82.6,124.8,64.8,-0.016,103.8,107.3

In [40]:
kenpom = CSV['kenpom']

kenpom['TeamName_lower'] = kenpom['TeamName'].str.lower()
kenpom = pd.merge(kenpom, teams_df[['TeamNameSpelling', 'TeamID']], left_on='TeamName_lower', right_on='TeamNameSpelling', how='left')

kenpom = kenpom.drop(['Unnamed: 0', 'TeamName_lower'], axis=1)
kenpom['TeamID'] = kenpom['TeamID'].astype('Int64')

null_team_ids_in_kenpom = kenpom['TeamID'].isna()
null_rows = kenpom[null_team_ids_in_kenpom]
if null_rows.size > 0:
    display(null_rows)
    unique_null_team_names = null_rows['TeamName'].unique()
    print(f'Cannot find team ids for following teams: \n{sorted(unique_null_team_names)}')

assert not null_team_ids_in_kenpom.any(), "Null 'TeamID' values found in kenpom data"
assert not kenpom.duplicated(subset=['Season', 'TeamID']).any(), "Duplicate 'Season' and 'TeamID' combinations found!"

In [41]:
seasons_available = kenpom['Season'].unique()
seasons_available

array([2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2021, 2022,
       2023, 2024, 2025])

# Feature engineering

In [42]:
# Home (H) -> 1
# Away (A) -> -1
# Neutral (N) -> 0
# Flipping location can be done by multipling by -1
location_to_number_map = { 'H': 1, 'A': -1, 'N': 0 }

regular_results = CSV['MRegularSeasonCompactResults']
tourney_results = CSV['MNCAATourneyCompactResults']
assert set(regular_results.columns) == set(tourney_results.columns), "regular_results and tourney_results have different columns"
combined_results = pd.concat([regular_results, tourney_results], ignore_index=True)

available_results = combined_results[combined_results['Season'].isin(seasons_available)].copy()
available_results['WLoc_num'] = available_results['WLoc'].map(location_to_number_map)
available_results['mov'] = available_results['WScore'] - available_results['LScore']
available_results['t1_win'] = 1
display(available_results)

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WLoc_num,mov,t1_win
113385,2011,7,1228,79,1414,65,H,0,1,14,1
113386,2011,7,1268,105,1370,76,H,0,1,29,1
113387,2011,7,1338,83,1348,75,H,0,1,8,1
113388,2011,7,1400,83,1298,52,H,0,1,31,1
113389,2011,9,1228,84,1405,45,H,0,1,39,1
...,...,...,...,...,...,...,...,...,...,...,...
195443,2024,146,1301,76,1181,64,N,0,0,12,1
195444,2024,146,1345,72,1397,66,N,0,0,6,1
195445,2024,152,1163,86,1104,72,N,0,0,14,1
195446,2024,152,1345,63,1301,50,N,0,0,13,1
195447,2024,154,1163,75,1345,60,N,0,0,15,1

In [43]:
# Rename MMasseyOrdinals as filename can be MMasseyOrdinals_something
if 'MMasseyOrdinals' not in CSV:
    CSV['MMasseyOrdinals'] = pd.concat(map(lambda x: CSV[x], fnmatch.filter(CSV.keys(), 'MMasseyOrdinals*')))

massey = CSV['MMasseyOrdinals']
available_massey = massey[massey['Season'].isin(seasons_available)]

# Group by ['Season', 'RankingDayNum', 'TeamID'] and find the average ordinal rank across all systems
real_massey = available_massey.groupby(['Season', 'RankingDayNum', 'TeamID'], as_index=False)['OrdinalRank'].mean()
assert not real_massey.duplicated(subset=['Season', 'RankingDayNum', 'TeamID']).any(), "Duplicate!"
display(real_massey.head())

   Season  RankingDayNum  TeamID  OrdinalRank
0    2011              0    1102        233.0
1    2011              0    1103        109.0
2    2011              0    1104         64.0
3    2011              0    1105        332.0
4    2011              0    1106        278.0

In [44]:
kenpom_columns = ['adj_o', 'adj_d', 'adj_tempo', 'luck', 'sos_adj_o', 'sos_adj_d']
team1_kenpom_columns = ['t1_' + kc for kc in kenpom_columns]
team2_kenpom_columns = ['t2_' + kc for kc in kenpom_columns]

In [46]:
relevant_available_results = available_results[['Season', 'DayNum', 'WTeamID', 'LTeamID', 'WLoc_num', 'mov', 't1_win']]
relevant_kenpom = kenpom[['Season', 'TeamID'] + kenpom_columns]
relevant_massey = real_massey[['Season', 'RankingDayNum', 'TeamID', 'OrdinalRank']]

In [48]:
joined_results = relevant_available_results.copy().rename(columns={'WLoc_num': 't1_loc_num'})

# add team1 (Wteam) kenpom stats
joined_results = pd.merge(joined_results, relevant_kenpom, left_on=['Season', 'WTeamID'], right_on=['Season', 'TeamID']).drop('TeamID', axis=1).rename(columns=dict(zip(kenpom_columns, team1_kenpom_columns)))

# add massey ordinal rank for team1
joined_results = pd.merge(joined_results, relevant_massey, left_on=['Season', 'DayNum', 'WTeamID'], right_on=['Season', 'RankingDayNum', 'TeamID'], how='left').drop(['TeamID', 'RankingDayNum'], axis=1).rename(columns={'OrdinalRank': 't1_OrdinalRank'})

# add team2 (Lteam) kenpom stats
joined_results = pd.merge(joined_results, relevant_kenpom, left_on=['Season', 'LTeamID'], right_on=['Season', 'TeamID']).drop('TeamID', axis=1).rename(columns=dict(zip(kenpom_columns, team2_kenpom_columns)))

# add massey ordinal rank for team2
joined_results = pd.merge(joined_results, relevant_massey, left_on=['Season', 'DayNum', 'LTeamID'], right_on=['Season', 'RankingDayNum', 'TeamID'], how='left').drop(['TeamID', 'RankingDayNum'], axis=1).rename(columns={'OrdinalRank': 't2_OrdinalRank'})

display(joined_results.tail())
print(joined_results.shape)

,Season,DayNum,WTeamID,LTeamID,t1_loc_num,mov,t1_win,t1_adj_o,t1_adj_d,t1_adj_tempo,...,t1_sos_adj_o,t1_sos_adj_d,t1_OrdinalRank,t2_adj_o,t2_adj_d,t2_adj_tempo,t2_luck,t2_sos_adj_o,t2_sos_adj_d,t2_OrdinalRank
75082,2024,146,1301,1181,0,12,1,112.6,101.8,68.7,...,109.6,103.5,NaN,122.4,97.5,67.1,-0.055,110.2,103.3,NaN
75083,2024,146,1345,1397,0,6,1,126.5,96.7,67.9,...,113.6,101.5,NaN,119.2,91.9,70.0,-0.037,113.4,103.0,NaN
75084,2024,152,1163,1104,0,14,1,125.6,96.1,64.6,...,110.3,103.0,NaN,128.2,102.7,72.9,-0.013,114.3,101.8,NaN
75085,2024,152,1345,1301,0,13,1,126.5,96.7,67.9,...,113.6,101.5,NaN,112.6,101.8,68.7,-0.019,109.6,103.5,NaN
75086,2024,154,1163,1345,0,15,1,125.6,96.1,64.6,...,110.3,103.0,NaN,126.5,96.7,67.9,0.046,113.6,101.5,NaN

(75087, 21)

In [49]:
# without massey ordinal ranks because it seems to be missing a lot of values - to add back, add 't1_OrdinalRank' and 't2_OrdinalRank'
data = joined_results[['t1_loc_num'] + team1_kenpom_columns + team2_kenpom_columns + ['mov', 't1_win']]
flipped_data = data.copy()
flipped_data[team1_kenpom_columns] = data[team2_kenpom_columns]
flipped_data[team2_kenpom_columns] = data[team1_kenpom_columns]

flipped_data['t1_loc_num'] = -data['t1_loc_num']
flipped_data['mov'] = -data['mov']
flipped_data['t1_win'] = 1 - data['t1_win']

display(data.head())
display(flipped_data.head())
print(data.shape, flipped_data.shape)

,t1_loc_num,t1_adj_o,t1_adj_d,t1_adj_tempo,t1_luck,t1_sos_adj_o,t1_sos_adj_d,t2_adj_o,t2_adj_d,t2_adj_tempo,t2_luck,t2_sos_adj_o,t2_sos_adj_d,mov,t1_win
0,1,112.7,90.6,66.9,-0.072,109.5,96.8,100.7,106.3,71.1,-0.049,100.2,102.4,14,1
1,1,109.2,91.2,71.6,-0.088,105.5,100.0,91.2,101.1,73.4,0.046,101.2,103.3,29,1
2,1,119.7,90.8,63.3,-0.003,106.4,97.6,102.4,98.2,67.7,0.064,102.9,100.9,8,1
3,1,114.0,85.3,67.2,-0.055,105.6,97.8,90.8,101.4,70.8,-0.038,99.8,104.9,31,1
4,1,112.7,90.6,66.9,-0.072,109.5,96.8,88.4,112.4,64.4,-0.038,100.0,101.1,39,1

,t1_loc_num,t1_adj_o,t1_adj_d,t1_adj_tempo,t1_luck,t1_sos_adj_o,t1_sos_adj_d,t2_adj_o,t2_adj_d,t2_adj_tempo,t2_luck,t2_sos_adj_o,t2_sos_adj_d,mov,t1_win
0,-1,100.7,106.3,71.1,-0.049,100.2,102.4,112.7,90.6,66.9,-0.072,109.5,96.8,-14,0
1,-1,91.2,101.1,73.4,0.046,101.2,103.3,109.2,91.2,71.6,-0.088,105.5,100.0,-29,0
2,-1,102.4,98.2,67.7,0.064,102.9,100.9,119.7,90.8,63.3,-0.003,106.4,97.6,-8,0
3,-1,90.8,101.4,70.8,-0.038,99.8,104.9,114.0,85.3,67.2,-0.055,105.6,97.8,-31,0
4,-1,88.4,112.4,64.4,-0.038,100.0,101.1,112.7,90.6,66.9,-0.072,109.5,96.8,-39,0

(75087, 15) (75087, 15)

In [51]:
augmented_data = pd.concat([data, flipped_data])
display(augmented_data)

,t1_loc_num,t1_adj_o,t1_adj_d,t1_adj_tempo,t1_luck,t1_sos_adj_o,t1_sos_adj_d,t2_adj_o,t2_adj_d,t2_adj_tempo,t2_luck,t2_sos_adj_o,t2_sos_adj_d,mov,t1_win
0,1,112.7,90.6,66.9,-0.072,109.5,96.8,100.7,106.3,71.1,-0.049,100.2,102.4,14,1
1,1,109.2,91.2,71.6,-0.088,105.5,100.0,91.2,101.1,73.4,0.046,101.2,103.3,29,1
2,1,119.7,90.8,63.3,-0.003,106.4,97.6,102.4,98.2,67.7,0.064,102.9,100.9,8,1
3,1,114.0,85.3,67.2,-0.055,105.6,97.8,90.8,101.4,70.8,-0.038,99.8,104.9,31,1
4,1,112.7,90.6,66.9,-0.072,109.5,96.8,88.4,112.4,64.4,-0.038,100.0,101.1,39,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75082,0,122.4,97.5,67.1,-0.055,110.2,103.3,112.6,101.8,68.7,-0.019,109.6,103.5,-12,0
75083,0,119.2,91.9,70.0,-0.037,113.4,103.0,126.5,96.7,67.9,0.046,113.6,101.5,-6,0
75084,0,128.2,102.7,72.9,-0.013,114.3,101.8,125.6,96.1,64.6,0.043,110.3,103.0,-14,0
75085,0,112.6,101.8,68.7,-0.019,109.6,103.5,126.5,96.7,67.9,0.046,113.6,101.5,-13,0
75086,0,126.5,96.7,67.9,0.046,113.6,101.5,125.6,96.1,64.6,0.043,110.3,103.0,-15,0

In [52]:
x = augmented_data.drop(['mov', 't1_win'], axis=1)
y_mov = augmented_data['mov']
y_win = augmented_data['t1_win']

# Splitting the data
x_train_mov, x_test_mov, y_train_mov, y_test_mov = train_test_split(x, y_mov, test_size=0.2, random_state=42)
x_train_win, x_test_win, y_train_win, y_test_win = train_test_split(x, y_win, test_size=0.2, random_state=42)

# Feature scaling
scaler = StandardScaler()

x_train_mov_scaled = scaler.fit_transform(x_train_mov)
x_test_mov_scaled = scaler.transform(x_test_mov)

x_train_win_scaled = scaler.fit_transform(x_train_mov)
x_test_win_scaled = scaler.transform(x_test_mov)

In [53]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Define the mov model
model_mov = keras.Sequential([
    layers.Dense(128, activation='relu', input_shape=(x_train_mov_scaled.shape[1],)),
    layers.Dropout(0.2),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(1)  # Output layer for regression should have 1 unit without activation
])

# Compile the mov model
model_mov.compile(optimizer='adam',
              loss='mean_squared_error',
              metrics=['mean_absolute_error'])

/Users/alan_chen/.pyenv/versions/3.10.14/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [75]:
history_mov = model_mov.fit(x_train_mov_scaled, y_train_mov, validation_split=0.2, epochs=EPOCHS, batch_size=32, verbose=1)

Epoch 1/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 672us/step - loss: 104.9980 - mean_absolute_error: 8.0504 - val_loss: 104.4428 - val_mean_absolute_error: 8.0238
Epoch 2/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 643us/step - loss: 105.4037 - mean_absolute_error: 8.0610 - val_loss: 104.5933 - val_mean_absolute_error: 8.0147
Epoch 3/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 665us/step - loss: 105.6197 - mean_absolute_error: 8.0648 - val_loss: 104.2702 - val_mean_absolute_error: 8.0118
Epoch 4/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 604us/step - loss: 104.6452 - mean_absolute_error: 8.0371 - val_loss: 104.4175 - val_mean_absolute_error: 8.0252
Epoch 5/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 606us/step - loss: 104.9969 - mean_absolute_error: 8.0563 - val_loss: 104.4750 - val_mean_absolute_error: 8.0104
Epoch 6/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 599us/step - loss: 104.5672 - mean_absolute_error: 8.0259 - val_loss: 104.3345 - val_mean_absolute_error: 8.0216
Epoch 7/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 594us/step - loss: 105.2204 - mean_absolute_error: 8.0529 - val_loss: 105.0408 - val_mean_absolute_error: 8.0569
Epoch 8/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 599us/step - loss: 105.5317 - mean_absolute_error: 8.0629 - val_loss: 104.5253 - val_mean_absolute_error: 8.0206
Epoch 9/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 594us/step - loss: 104.9059 - mean_absolute_error: 8.0202 - val_loss: 104.6523 - val_mean_absolute_error: 8.0171
Epoch 10/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 605us/step - loss: 104.8575 - mean_absolute_error: 8.0427 - val_loss: 104.8515 - val_mean_absolute_error: 8.0282
Epoch 11/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 585us/step - loss: 104.5645 - mean_absolute_error: 8.0202 - val_loss: 104.6066 - val_mean_absolute_error: 8.0349
Epoch 12/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 620us/step - loss: 104.1561 - mean_absolute_error: 8.0113 - val_loss: 104.3216 - val_mean_absolute_error: 8.0169
Epoch 13/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 586us/step - loss: 104.3519 - mean_absolute_error: 8.0279 - val_loss: 104.6855 - val_mean_absolute_error: 8.0363
Epoch 14/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 623us/step - loss: 104.4191 - mean_absolute_error: 8.0255 - val_loss: 104.2047 - val_mean_absolute_error: 8.0166
Epoch 15/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 573us/step - loss: 104.5518 - mean_absolute_error: 8.0333 - val_loss: 104.2347 - val_mean_absolute_error: 8.0086
Epoch 16/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 616us/step - loss: 104.6654 - mean_absolute_error: 8.0336 - val_loss: 104.9859 - val_mean_absolute_error: 8.0540
Epoch 17/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 573us/step - loss: 105.0798 - mean_absolute_error: 8.0474 - val_loss: 104.4141 - val_mean_absolute_error: 8.0108
Epoch 18/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 624us/step - loss: 104.7800 - mean_absolute_error: 8.0235 - val_loss: 104.8622 - val_mean_absolute_error: 8.0231
Epoch 19/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 579us/step - loss: 105.1855 - mean_absolute_error: 8.0445 - val_loss: 104.6841 - val_mean_absolute_error: 8.0437
Epoch 20/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 614us/step - loss: 104.4492 - mean_absolute_error: 8.0105 - val_loss: 104.4183 - val_mean_absolute_error: 8.0244
Epoch 21/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 583us/step - loss: 105.0119 - mean_absolute_error: 8.0478 - val_loss: 104.3512 - val_mean_absolute_error: 8.0221
Epoch 22/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 612us/step - loss: 104.2654 - mean_absolute_error: 8.0129 - val_loss: 104.3554 - val_mean_absolute_error: 8.0131
Epoch 23/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 583us/step - loss: 104.2245 - mean_absolute_error: 8.0174 - val_loss: 104.5919 - val_mean_absolute_error: 8.0209
Epoch 24/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 598us/step - loss: 104.1750 - mean_absolute_error: 8.0211 - val_loss: 105.0657 - val_mean_absolute_error: 8.0472
Epoch 25/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 591us/step - loss: 105.2010 - mean_absolute_error: 8.0636 - val_loss: 104.6964 - val_mean_absolute_error: 8.0185
Epoch 26/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 601us/step - loss: 104.5297 - mean_absolute_error: 8.0332 - val_loss: 104.5721 - val_mean_absolute_error: 8.0170
Epoch 27/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 603us/step - loss: 103.9203 - mean_absolute_error: 7.9988 - val_loss: 105.3791 - val_mean_absolute_error: 8.0723
Epoch 28/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 596us/step - loss: 105.1145 - mean_absolute_error: 8.0435 - val_loss: 104.5880 - val_mean_absolute_error: 8.0239
Epoch 29/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 600us/step - loss: 103.8092 - mean_absolute_error: 7.9921 - val_loss: 104.7173 - val_mean_absolute_error: 8.0218
Epoch 30/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 594us/step - loss: 103.9595 - mean_absolute_error: 8.0105 - val_loss: 104.9483 - val_mean_absolute_error: 8.0367
Epoch 31/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 651us/step - loss: 103.9335 - mean_absolute_error: 8.0119 - val_loss: 104.6032 - val_mean_absolute_error: 8.0216
Epoch 32/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 661us/step - loss: 105.7920 - mean_absolute_error: 8.0542 - val_loss: 104.7504 - val_mean_absolute_error: 8.0429
Epoch 33/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 670us/step - loss: 103.7089 - mean_absolute_error: 7.9880 - val_loss: 104.3317 - val_mean_absolute_error: 8.0146
Epoch 34/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 662us/step - loss: 104.6400 - mean_absolute_error: 8.0270 - val_loss: 104.3722 - val_mean_absolute_error: 8.0128
Epoch 35/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 650us/step - loss: 104.7338 - mean_absolute_error: 8.0277 - val_loss: 104.5813 - val_mean_absolute_error: 8.0206
Epoch 36/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 654us/step - loss: 105.0568 - mean_absolute_error: 8.0482 - val_loss: 104.4687 - val_mean_absolute_error: 8.0242
Epoch 37/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 662us/step - loss: 104.5613 - mean_absolute_error: 8.0235 - val_loss: 104.5754 - val_mean_absolute_error: 8.0232
Epoch 38/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 659us/step - loss: 104.9172 - mean_absolute_error: 8.0430 - val_loss: 104.7760 - val_mean_absolute_error: 8.0357
Epoch 39/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 664us/step - loss: 104.5100 - mean_absolute_error: 8.0226 - val_loss: 105.2065 - val_mean_absolute_error: 8.0346
Epoch 40/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 657us/step - loss: 105.2743 - mean_absolute_error: 8.0402 - val_loss: 104.6368 - val_mean_absolute_error: 8.0297
Epoch 41/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 692us/step - loss: 104.1948 - mean_absolute_error: 8.0109 - val_loss: 104.9183 - val_mean_absolute_error: 8.0358
Epoch 42/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 594us/step - loss: 103.9436 - mean_absolute_error: 8.0182 - val_loss: 104.4910 - val_mean_absolute_error: 8.0203
Epoch 43/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 571us/step - loss: 103.8777 - mean_absolute_error: 8.0010 - val_loss: 105.0418 - val_mean_absolute_error: 8.0275
Epoch 44/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 563us/step - loss: 104.6652 - mean_absolute_error: 8.0405 - val_loss: 104.6854 - val_mean_absolute_error: 8.0326
Epoch 45/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 572us/step - loss: 104.3432 - mean_absolute_error: 8.0287 - val_loss: 104.5057 - val_mean_absolute_error: 8.0157
Epoch 46/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 572us/step - loss: 103.4958 - mean_absolute_error: 7.9944 - val_loss: 104.6451 - val_mean_absolute_error: 8.0204
Epoch 47/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 573us/step - loss: 103.7689 - mean_absolute_error: 7.9995 - val_loss: 104.6508 - val_mean_absolute_error: 8.0327
Epoch 48/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 588us/step - loss: 103.0201 - mean_absolute_error: 7.9772 - val_loss: 105.0569 - val_mean_absolute_error: 8.0452
Epoch 49/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 607us/step - loss: 102.9143 - mean_absolute_error: 7.9788 - val_loss: 104.9855 - val_mean_absolute_error: 8.0456
Epoch 50/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 601us/step - loss: 103.1524 - mean_absolute_error: 7.9684 - val_loss: 104.7208 - val_mean_absolute_error: 8.0328
Epoch 51/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 585us/step - loss: 103.5067 - mean_absolute_error: 7.9703 - val_loss: 104.8545 - val_mean_absolute_error: 8.0303
Epoch 52/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 605us/step - loss: 104.0056 - mean_absolute_error: 8.0144 - val_loss: 104.4509 - val_mean_absolute_error: 8.0204
Epoch 53/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 605us/step - loss: 103.8057 - mean_absolute_error: 7.9858 - val_loss: 104.9343 - val_mean_absolute_error: 8.0318
Epoch 54/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 624us/step - loss: 103.7376 - mean_absolute_error: 7.9996 - val_loss: 104.7739 - val_mean_absolute_error: 8.0256
Epoch 55/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 642us/step - loss: 104.7396 - mean_absolute_error: 8.0349 - val_loss: 104.6912 - val_mean_absolute_error: 8.0273
Epoch 56/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 611us/step - loss: 104.2951 - mean_absolute_error: 8.0107 - val_loss: 104.6095 - val_mean_absolute_error: 8.0207
Epoch 57/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 643us/step - loss: 103.8223 - mean_absolute_error: 7.9990 - val_loss: 105.0938 - val_mean_absolute_error: 8.0247
Epoch 58/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 607us/step - loss: 103.8689 - mean_absolute_error: 8.0064 - val_loss: 104.6687 - val_mean_absolute_error: 8.0237
Epoch 59/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 585us/step - loss: 103.7667 - mean_absolute_error: 8.0026 - val_loss: 104.7629 - val_mean_absolute_error: 8.0277
Epoch 60/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 604us/step - loss: 103.9416 - mean_absolute_error: 8.0041 - val_loss: 104.9891 - val_mean_absolute_error: 8.0463
Epoch 61/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 590us/step - loss: 103.8472 - mean_absolute_error: 7.9950 - val_loss: 105.0576 - val_mean_absolute_error: 8.0511
Epoch 62/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 597us/step - loss: 103.8325 - mean_absolute_error: 8.0121 - val_loss: 105.0039 - val_mean_absolute_error: 8.0420
Epoch 63/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 590us/step - loss: 103.0027 - mean_absolute_error: 7.9660 - val_loss: 104.8518 - val_mean_absolute_error: 8.0366
Epoch 64/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 585us/step - loss: 103.6697 - mean_absolute_error: 7.9846 - val_loss: 104.6930 - val_mean_absolute_error: 8.0193
Epoch 65/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 601us/step - loss: 103.5494 - mean_absolute_error: 7.9830 - val_loss: 104.6203 - val_mean_absolute_error: 8.0299
Epoch 66/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 595us/step - loss: 104.3352 - mean_absolute_error: 8.0185 - val_loss: 104.7901 - val_mean_absolute_error: 8.0293
Epoch 67/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 616us/step - loss: 103.4704 - mean_absolute_error: 7.9920 - val_loss: 105.0229 - val_mean_absolute_error: 8.0299
Epoch 68/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 628us/step - loss: 103.4257 - mean_absolute_error: 7.9744 - val_loss: 104.8513 - val_mean_absolute_error: 8.0426
Epoch 69/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 626us/step - loss: 103.4289 - mean_absolute_error: 7.9917 - val_loss: 104.8849 - val_mean_absolute_error: 8.0376
Epoch 70/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 648us/step - loss: 103.8842 - mean_absolute_error: 7.9955 - val_loss: 105.1175 - val_mean_absolute_error: 8.0465
Epoch 71/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 634us/step - loss: 104.4808 - mean_absolute_error: 8.0399 - val_loss: 105.6125 - val_mean_absolute_error: 8.0641
Epoch 72/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 641us/step - loss: 104.0497 - mean_absolute_error: 8.0132 - val_loss: 105.2584 - val_mean_absolute_error: 8.0322
Epoch 73/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 618us/step - loss: 104.4756 - mean_absolute_error: 8.0202 - val_loss: 104.7339 - val_mean_absolute_error: 8.0304
Epoch 74/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 638us/step - loss: 103.7437 - mean_absolute_error: 7.9964 - val_loss: 105.6455 - val_mean_absolute_error: 8.0736
Epoch 75/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 576us/step - loss: 104.4798 - mean_absolute_error: 8.0333 - val_loss: 104.9749 - val_mean_absolute_error: 8.0413
Epoch 76/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 626us/step - loss: 103.1503 - mean_absolute_error: 7.9720 - val_loss: 105.1526 - val_mean_absolute_error: 8.0582
Epoch 77/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 587us/step - loss: 103.4310 - mean_absolute_error: 7.9851 - val_loss: 104.8862 - val_mean_absolute_error: 8.0274
Epoch 78/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 605us/step - loss: 104.1293 - mean_absolute_error: 8.0107 - val_loss: 105.0854 - val_mean_absolute_error: 8.0424
Epoch 79/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 645us/step - loss: 103.5237 - mean_absolute_error: 7.9887 - val_loss: 105.2828 - val_mean_absolute_error: 8.0502
Epoch 80/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 625us/step - loss: 103.8512 - mean_absolute_error: 8.0051 - val_loss: 105.5962 - val_mean_absolute_error: 8.0680
Epoch 81/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 605us/step - loss: 104.1271 - mean_absolute_error: 8.0174 - val_loss: 105.5662 - val_mean_absolute_error: 8.0419
Epoch 82/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 579us/step - loss: 103.7163 - mean_absolute_error: 8.0113 - val_loss: 104.9952 - val_mean_absolute_error: 8.0394
Epoch 83/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 582us/step - loss: 104.0772 - mean_absolute_error: 8.0035 - val_loss: 105.3670 - val_mean_absolute_error: 8.0672
Epoch 84/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 597us/step - loss: 102.6065 - mean_absolute_error: 7.9569 - val_loss: 105.3211 - val_mean_absolute_error: 8.0559
Epoch 85/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 583us/step - loss: 103.6583 - mean_absolute_error: 8.0013 - val_loss: 104.8977 - val_mean_absolute_error: 8.0283
Epoch 86/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 586us/step - loss: 103.5985 - mean_absolute_error: 7.9952 - val_loss: 105.2867 - val_mean_absolute_error: 8.0418
Epoch 87/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 606us/step - loss: 103.9436 - mean_absolute_error: 7.9983 - val_loss: 104.9928 - val_mean_absolute_error: 8.0307
Epoch 88/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 619us/step - loss: 104.2348 - mean_absolute_error: 7.9965 - val_loss: 105.0274 - val_mean_absolute_error: 8.0305
Epoch 89/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 628us/step - loss: 104.1623 - mean_absolute_error: 8.0077 - val_loss: 105.1987 - val_mean_absolute_error: 8.0521
Epoch 90/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 623us/step - loss: 102.7182 - mean_absolute_error: 7.9575 - val_loss: 105.2952 - val_mean_absolute_error: 8.0417
Epoch 91/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 638us/step - loss: 103.1273 - mean_absolute_error: 7.9758 - val_loss: 105.1782 - val_mean_absolute_error: 8.0507
Epoch 92/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 612us/step - loss: 104.2681 - mean_absolute_error: 8.0014 - val_loss: 104.9221 - val_mean_absolute_error: 8.0308
Epoch 93/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 647us/step - loss: 103.3752 - mean_absolute_error: 7.9762 - val_loss: 104.8485 - val_mean_absolute_error: 8.0307
Epoch 94/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 595us/step - loss: 102.8367 - mean_absolute_error: 7.9644 - val_loss: 105.0017 - val_mean_absolute_error: 8.0334
Epoch 95/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 590us/step - loss: 102.4178 - mean_absolute_error: 7.9491 - val_loss: 105.4420 - val_mean_absolute_error: 8.0519
Epoch 96/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 595us/step - loss: 103.2843 - mean_absolute_error: 7.9974 - val_loss: 105.1696 - val_mean_absolute_error: 8.0344
Epoch 97/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 586us/step - loss: 103.5557 - mean_absolute_error: 7.9817 - val_loss: 104.9956 - val_mean_absolute_error: 8.0372
Epoch 98/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 603us/step - loss: 103.2834 - mean_absolute_error: 7.9894 - val_loss: 104.8602 - val_mean_absolute_error: 8.0241
Epoch 99/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 588us/step - loss: 103.3917 - mean_absolute_error: 7.9803 - val_loss: 105.0937 - val_mean_absolute_error: 8.0489
Epoch 100/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 651us/step - loss: 103.1535 - mean_absolute_error: 7.9773 - val_loss: 105.1607 - val_mean_absolute_error: 8.0435

In [76]:
model_win = keras.Sequential([
    layers.Dense(128, activation='relu', input_shape=(x_train_win_scaled.shape[1],)),
    layers.Dropout(0.2),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(1, activation='sigmoid')  # Changed for binary classification
])

model_win.compile(optimizer='adam',
              loss='binary_crossentropy',  # Changed for binary classification
              metrics=['accuracy'])  # Common metric for classification

/Users/alan_chen/.pyenv/versions/3.10.14/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [77]:
history_win = model_win.fit(x_train_win_scaled, y_train_win, validation_split=0.2, epochs=EPOCHS, batch_size=32, verbose=1)

Epoch 1/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 699us/step - accuracy: 0.7646 - loss: 0.4835 - val_accuracy: 0.7723 - val_loss: 0.4668
Epoch 2/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 680us/step - accuracy: 0.7732 - loss: 0.4660 - val_accuracy: 0.7738 - val_loss: 0.4671
Epoch 3/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 678us/step - accuracy: 0.7739 - loss: 0.4665 - val_accuracy: 0.7718 - val_loss: 0.4670
Epoch 4/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 664us/step - accuracy: 0.7729 - loss: 0.4660 - val_accuracy: 0.7716 - val_loss: 0.4688
Epoch 5/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 665us/step - accuracy: 0.7747 - loss: 0.4672 - val_accuracy: 0.7736 - val_loss: 0.4663
Epoch 6/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 670us/step - accuracy: 0.7751 - loss: 0.4634 - val_accuracy: 0.7726 - val_loss: 0.4671
Epoch 7/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 677us/step - accuracy: 0.7747 - loss: 0.4627 - val_accuracy: 0.7723 - val_loss: 0.4683
Epoch 8/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 672us/step - accuracy: 0.7752 - loss: 0.4630 - val_accuracy: 0.7727 - val_loss: 0.4664
Epoch 9/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 667us/step - accuracy: 0.7768 - loss: 0.4617 - val_accuracy: 0.7711 - val_loss: 0.4660
Epoch 10/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 663us/step - accuracy: 0.7758 - loss: 0.4621 - val_accuracy: 0.7706 - val_loss: 0.4678
Epoch 11/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 646us/step - accuracy: 0.7754 - loss: 0.4612 - val_accuracy: 0.7714 - val_loss: 0.4679
Epoch 12/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 651us/step - accuracy: 0.7754 - loss: 0.4634 - val_accuracy: 0.7721 - val_loss: 0.4661
Epoch 13/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 650us/step - accuracy: 0.7749 - loss: 0.4632 - val_accuracy: 0.7721 - val_loss: 0.4708
Epoch 14/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 663us/step - accuracy: 0.7754 - loss: 0.4618 - val_accuracy: 0.7718 - val_loss: 0.4667
Epoch 15/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 653us/step - accuracy: 0.7749 - loss: 0.4631 - val_accuracy: 0.7732 - val_loss: 0.4678
Epoch 16/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 685us/step - accuracy: 0.7773 - loss: 0.4598 - val_accuracy: 0.7727 - val_loss: 0.4665
Epoch 17/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 668us/step - accuracy: 0.7744 - loss: 0.4649 - val_accuracy: 0.7717 - val_loss: 0.4665
Epoch 18/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 659us/step - accuracy: 0.7736 - loss: 0.4636 - val_accuracy: 0.7726 - val_loss: 0.4683
Epoch 19/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 660us/step - accuracy: 0.7767 - loss: 0.4607 - val_accuracy: 0.7715 - val_loss: 0.4671
Epoch 20/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 666us/step - accuracy: 0.7767 - loss: 0.4635 - val_accuracy: 0.7718 - val_loss: 0.4667
Epoch 21/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 671us/step - accuracy: 0.7783 - loss: 0.4586 - val_accuracy: 0.7718 - val_loss: 0.4700
Epoch 22/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 687us/step - accuracy: 0.7774 - loss: 0.4626 - val_accuracy: 0.7713 - val_loss: 0.4680
Epoch 23/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 658us/step - accuracy: 0.7784 - loss: 0.4575 - val_accuracy: 0.7710 - val_loss: 0.4666
Epoch 24/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 662us/step - accuracy: 0.7791 - loss: 0.4594 - val_accuracy: 0.7710 - val_loss: 0.4686
Epoch 25/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 663us/step - accuracy: 0.7766 - loss: 0.4613 - val_accuracy: 0.7709 - val_loss: 0.4674
Epoch 26/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 663us/step - accuracy: 0.7768 - loss: 0.4602 - val_accuracy: 0.7714 - val_loss: 0.4678
Epoch 27/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 660us/step - accuracy: 0.7750 - loss: 0.4620 - val_accuracy: 0.7706 - val_loss: 0.4672
Epoch 28/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 658us/step - accuracy: 0.7772 - loss: 0.4608 - val_accuracy: 0.7708 - val_loss: 0.4692
Epoch 29/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 656us/step - accuracy: 0.7766 - loss: 0.4619 - val_accuracy: 0.7708 - val_loss: 0.4694
Epoch 30/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 667us/step - accuracy: 0.7766 - loss: 0.4593 - val_accuracy: 0.7709 - val_loss: 0.4676
Epoch 31/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 668us/step - accuracy: 0.7778 - loss: 0.4596 - val_accuracy: 0.7713 - val_loss: 0.4681
Epoch 32/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 660us/step - accuracy: 0.7768 - loss: 0.4606 - val_accuracy: 0.7716 - val_loss: 0.4699
Epoch 33/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 683us/step - accuracy: 0.7765 - loss: 0.4612 - val_accuracy: 0.7716 - val_loss: 0.4675
Epoch 34/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 681us/step - accuracy: 0.7790 - loss: 0.4591 - val_accuracy: 0.7713 - val_loss: 0.4677
Epoch 35/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 672us/step - accuracy: 0.7789 - loss: 0.4587 - val_accuracy: 0.7706 - val_loss: 0.4684
Epoch 36/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 666us/step - accuracy: 0.7797 - loss: 0.4581 - val_accuracy: 0.7708 - val_loss: 0.4689
Epoch 37/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 679us/step - accuracy: 0.7758 - loss: 0.4606 - val_accuracy: 0.7713 - val_loss: 0.4693
Epoch 38/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 684us/step - accuracy: 0.7788 - loss: 0.4566 - val_accuracy: 0.7702 - val_loss: 0.4691
Epoch 39/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 671us/step - accuracy: 0.7773 - loss: 0.4589 - val_accuracy: 0.7695 - val_loss: 0.4680
Epoch 40/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 668us/step - accuracy: 0.7768 - loss: 0.4603 - val_accuracy: 0.7706 - val_loss: 0.4695
Epoch 41/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 675us/step - accuracy: 0.7786 - loss: 0.4581 - val_accuracy: 0.7706 - val_loss: 0.4676
Epoch 42/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 654us/step - accuracy: 0.7771 - loss: 0.4579 - val_accuracy: 0.7701 - val_loss: 0.4687
Epoch 43/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 668us/step - accuracy: 0.7795 - loss: 0.4569 - val_accuracy: 0.7692 - val_loss: 0.4689
Epoch 44/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 672us/step - accuracy: 0.7766 - loss: 0.4588 - val_accuracy: 0.7701 - val_loss: 0.4679
Epoch 45/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 678us/step - accuracy: 0.7767 - loss: 0.4618 - val_accuracy: 0.7696 - val_loss: 0.4699
Epoch 46/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 678us/step - accuracy: 0.7795 - loss: 0.4571 - val_accuracy: 0.7694 - val_loss: 0.4695
Epoch 47/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 673us/step - accuracy: 0.7768 - loss: 0.4602 - val_accuracy: 0.7693 - val_loss: 0.4699
Epoch 48/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 660us/step - accuracy: 0.7793 - loss: 0.4578 - val_accuracy: 0.7698 - val_loss: 0.4694
Epoch 49/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 665us/step - accuracy: 0.7793 - loss: 0.4549 - val_accuracy: 0.7703 - val_loss: 0.4691
Epoch 50/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 675us/step - accuracy: 0.7801 - loss: 0.4574 - val_accuracy: 0.7709 - val_loss: 0.4691
Epoch 51/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 666us/step - accuracy: 0.7793 - loss: 0.4584 - val_accuracy: 0.7691 - val_loss: 0.4700
Epoch 52/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 660us/step - accuracy: 0.7798 - loss: 0.4572 - val_accuracy: 0.7691 - val_loss: 0.4697
Epoch 53/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 664us/step - accuracy: 0.7795 - loss: 0.4543 - val_accuracy: 0.7689 - val_loss: 0.4694
Epoch 54/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 610us/step - accuracy: 0.7804 - loss: 0.4567 - val_accuracy: 0.7697 - val_loss: 0.4683
Epoch 55/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 666us/step - accuracy: 0.7772 - loss: 0.4599 - val_accuracy: 0.7699 - val_loss: 0.4684
Epoch 56/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 682us/step - accuracy: 0.7802 - loss: 0.4552 - val_accuracy: 0.7692 - val_loss: 0.4689
Epoch 57/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 678us/step - accuracy: 0.7785 - loss: 0.4572 - val_accuracy: 0.7688 - val_loss: 0.4680
Epoch 58/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 673us/step - accuracy: 0.7788 - loss: 0.4567 - val_accuracy: 0.7699 - val_loss: 0.4686
Epoch 59/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 667us/step - accuracy: 0.7780 - loss: 0.4574 - val_accuracy: 0.7688 - val_loss: 0.4706
Epoch 60/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 683us/step - accuracy: 0.7770 - loss: 0.4587 - val_accuracy: 0.7701 - val_loss: 0.4693
Epoch 61/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 660us/step - accuracy: 0.7779 - loss: 0.4545 - val_accuracy: 0.7693 - val_loss: 0.4693
Epoch 62/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 683us/step - accuracy: 0.7813 - loss: 0.4549 - val_accuracy: 0.7690 - val_loss: 0.4718
Epoch 63/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 687us/step - accuracy: 0.7800 - loss: 0.4564 - val_accuracy: 0.7695 - val_loss: 0.4694
Epoch 64/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 695us/step - accuracy: 0.7778 - loss: 0.4578 - val_accuracy: 0.7704 - val_loss: 0.4702
Epoch 65/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 699us/step - accuracy: 0.7784 - loss: 0.4593 - val_accuracy: 0.7689 - val_loss: 0.4702
Epoch 66/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 684us/step - accuracy: 0.7779 - loss: 0.4567 - val_accuracy: 0.7684 - val_loss: 0.4699
Epoch 67/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 672us/step - accuracy: 0.7794 - loss: 0.4559 - val_accuracy: 0.7684 - val_loss: 0.4697
Epoch 68/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 672us/step - accuracy: 0.7803 - loss: 0.4553 - val_accuracy: 0.7687 - val_loss: 0.4696
Epoch 69/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 664us/step - accuracy: 0.7795 - loss: 0.4570 - val_accuracy: 0.7681 - val_loss: 0.4702
Epoch 70/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 684us/step - accuracy: 0.7823 - loss: 0.4520 - val_accuracy: 0.7686 - val_loss: 0.4705
Epoch 71/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 660us/step - accuracy: 0.7811 - loss: 0.4552 - val_accuracy: 0.7702 - val_loss: 0.4687
Epoch 72/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 677us/step - accuracy: 0.7817 - loss: 0.4556 - val_accuracy: 0.7691 - val_loss: 0.4700
Epoch 73/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 673us/step - accuracy: 0.7839 - loss: 0.4507 - val_accuracy: 0.7694 - val_loss: 0.4700
Epoch 74/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 680us/step - accuracy: 0.7813 - loss: 0.4534 - val_accuracy: 0.7691 - val_loss: 0.4693
Epoch 75/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 670us/step - accuracy: 0.7810 - loss: 0.4539 - val_accuracy: 0.7692 - val_loss: 0.4721
Epoch 76/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 678us/step - accuracy: 0.7780 - loss: 0.4567 - val_accuracy: 0.7688 - val_loss: 0.4714
Epoch 77/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 683us/step - accuracy: 0.7821 - loss: 0.4528 - val_accuracy: 0.7697 - val_loss: 0.4707
Epoch 78/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 665us/step - accuracy: 0.7824 - loss: 0.4541 - val_accuracy: 0.7684 - val_loss: 0.4701
Epoch 79/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 680us/step - accuracy: 0.7835 - loss: 0.4510 - val_accuracy: 0.7696 - val_loss: 0.4698
Epoch 80/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 685us/step - accuracy: 0.7818 - loss: 0.4545 - val_accuracy: 0.7703 - val_loss: 0.4697
Epoch 81/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 684us/step - accuracy: 0.7824 - loss: 0.4527 - val_accuracy: 0.7696 - val_loss: 0.4702
Epoch 82/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 679us/step - accuracy: 0.7787 - loss: 0.4570 - val_accuracy: 0.7680 - val_loss: 0.4712
Epoch 83/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 682us/step - accuracy: 0.7822 - loss: 0.4540 - val_accuracy: 0.7683 - val_loss: 0.4705
Epoch 84/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 665us/step - accuracy: 0.7805 - loss: 0.4559 - val_accuracy: 0.7691 - val_loss: 0.4705
Epoch 85/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 662us/step - accuracy: 0.7798 - loss: 0.4555 - val_accuracy: 0.7697 - val_loss: 0.4710
Epoch 86/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 665us/step - accuracy: 0.7816 - loss: 0.4547 - val_accuracy: 0.7686 - val_loss: 0.4704
Epoch 87/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 666us/step - accuracy: 0.7817 - loss: 0.4525 - val_accuracy: 0.7677 - val_loss: 0.4731
Epoch 88/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 661us/step - accuracy: 0.7824 - loss: 0.4534 - val_accuracy: 0.7681 - val_loss: 0.4721
Epoch 89/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 670us/step - accuracy: 0.7830 - loss: 0.4521 - val_accuracy: 0.7690 - val_loss: 0.4714
Epoch 90/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 659us/step - accuracy: 0.7824 - loss: 0.4534 - val_accuracy: 0.7683 - val_loss: 0.4715
Epoch 91/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 661us/step - accuracy: 0.7811 - loss: 0.4554 - val_accuracy: 0.7683 - val_loss: 0.4712
Epoch 92/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 642us/step - accuracy: 0.7804 - loss: 0.4543 - val_accuracy: 0.7688 - val_loss: 0.4727
Epoch 93/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 626us/step - accuracy: 0.7831 - loss: 0.4517 - val_accuracy: 0.7699 - val_loss: 0.4711
Epoch 94/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 656us/step - accuracy: 0.7820 - loss: 0.4532 - val_accuracy: 0.7670 - val_loss: 0.4713
Epoch 95/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 647us/step - accuracy: 0.7795 - loss: 0.4549 - val_accuracy: 0.7696 - val_loss: 0.4711
Epoch 96/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 643us/step - accuracy: 0.7827 - loss: 0.4518 - val_accuracy: 0.7684 - val_loss: 0.4711
Epoch 97/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 685us/step - accuracy: 0.7812 - loss: 0.4550 - val_accuracy: 0.7685 - val_loss: 0.4709
Epoch 98/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 693us/step - accuracy: 0.7822 - loss: 0.4516 - val_accuracy: 0.7690 - val_loss: 0.4709
Epoch 99/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 683us/step - accuracy: 0.7825 - loss: 0.4527 - val_accuracy: 0.7697 - val_loss: 0.4710
Epoch 100/100
3004/3004 ━━━━━━━━━━━━━━━━━━━━ 2s 644us/step - accuracy: 0.7826 - loss: 0.4526 - val_accuracy: 0.7687 - val_loss: 0.4726

In [78]:
# Evaluate the model
test_loss_mov, test_mae = model_mov.evaluate(x_test_mov, y_test_mov, verbose=1)
print('\nTest loss mov:', test_mae)

test_loss_win, test_accuracy = model_win.evaluate(x_test_win, y_test_win, verbose=1)
print(f'Test Loss win: {test_loss_win}, Test Accuracy: {test_accuracy}')

939/939 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - loss: 313.9200 - mean_absolute_error: 14.5351

Test loss mov: 14.50028133392334
939/939 ━━━━━━━━━━━━━━━━━━━━ 0s 408us/step - accuracy: 0.4978 - loss: 9.1980
Test Loss win: 9.17327880859375, Test Accuracy: 0.5004494786262512

In [79]:
def get_team_kenpom_by_id(teamID, season=SEASON):
    return kenpom.loc[(kenpom['Season'] == season) & (kenpom['TeamID'] == teamID)].iloc[0]

def get_team_kenpom_by_team_name(team_name, season=SEASON):
    team = teams_df.loc[teams_df['TeamNameSpelling'] == team_name.lower()]
    assert not team.empty, f"No team found with spelling {team_name}"
    teamID = team.iloc[0]['TeamID']
    
    return get_team_kenpom_by_id(teamID, season)

def get_team_features(team_kenpom):
    return [team_kenpom['adj_o'], team_kenpom['adj_d'], team_kenpom['adj_tempo'], team_kenpom['luck'], team_kenpom['sos_adj_o'], team_kenpom['sos_adj_d']]
#     return [team_kenpom[kenpom_columns]]
    
def is_number(value):
    return isinstance(value, (int, float, complex))

def mov_to_win_prob(mov, k=0.14):
    """
    Convert margin of victory to win probability.
    
    :param mov: Predicted margin of victory (positive for Team 1 win, negative for Team 2 win)
    :param k: Constant determining the steepness of the function
    :return: Probability of Team 1 winning
    """
    win_prob = 1 / (1 + np.exp(-k * mov))
    return win_prob

def predict_matchup(team1, team2, season=SEASON, location=0, label_type=LABEL_TYPE):
    if is_number(team1):
        team1_kenpom = get_team_kenpom_by_id(team1, season)
    else:
        team1_kenpom = get_team_kenpom_by_team_name(team1, season)
    if is_number(team2):
        team2_kenpom = get_team_kenpom_by_id(team2, season)
    else:
        team2_kenpom = get_team_kenpom_by_team_name(team2, season)
        
    
    team1_features = get_team_features(team1_kenpom)
    team2_features = get_team_features(team2_kenpom)
    
    column_names = ['t1_loc_num'] + team1_kenpom_columns + team2_kenpom_columns
    
    full_features = [location] + team1_features + team2_features
    full_features_flipped = [-location] + team2_features + team1_features
    
    full_features_scaled = scaler.transform(pd.DataFrame([full_features], columns=column_names))
    full_features_flipped_scaled = scaler.transform(pd.DataFrame([full_features_flipped], columns=column_names))

    if (label_type == LabelType.MARGIN_OF_VICTORY):
        predicted_mov = model_mov.predict(full_features_scaled, verbose=0)[0][0]
        predicted_mov_flipped = model_mov.predict(full_features_flipped_scaled, verbose=0)[0][0]
        final_predicted_mov = (predicted_mov - predicted_mov_flipped) / 2
        derived_win = mov_to_win_prob(final_predicted_mov)
        
        return derived_win

    elif (label_type == LabelType.WIN_PROBABILITY):
        predicted_win = model_win.predict(full_features_scaled, verbose=0)[0][0]
        predicted_win_flipped = model_win.predict(full_features_flipped_scaled, verbose=0)[0][0]
        final_predicted_win = (predicted_win + (1.0 - predicted_win_flipped)) / 2 

        return final_predicted_win

    return None

In [95]:
print(predict_matchup(1222, 1188, SEASON, 0, LabelType.MARGIN_OF_VICTORY)) # houston vs siue
print(predict_matchup('houston', 'siue', SEASON, 0, LabelType.MARGIN_OF_VICTORY))
print(predict_matchup('duke', 'florida', SEASON, 0, LabelType.MARGIN_OF_VICTORY))
print(predict_matchup('florida', 'duke', SEASON, 0, LabelType.MARGIN_OF_VICTORY))
print(predict_matchup('ole miss', 'unc', SEASON, 0, LabelType.MARGIN_OF_VICTORY))
print(predict_matchup('unc', 'ole miss', SEASON, 0, LabelType.MARGIN_OF_VICTORY))

0.9838537
0.9838537
0.5605852
0.4394148
0.5378832
0.46211678

In [96]:
print(predict_matchup(1222, 1188, SEASON, 0, LabelType.WIN_PROBABILITY)) # houston vs siue
print(predict_matchup('houston', 'siue', SEASON, 0, LabelType.WIN_PROBABILITY))
print(predict_matchup('duke', 'florida', SEASON, 0, LabelType.WIN_PROBABILITY))
print(predict_matchup('florida', 'duke', SEASON, 0, LabelType.WIN_PROBABILITY))
print(predict_matchup('ole miss', 'unc', SEASON, 0, LabelType.WIN_PROBABILITY))
print(predict_matchup('unc', 'ole miss', SEASON, 0, LabelType.WIN_PROBABILITY))

0.9969006
0.9969006
0.5195602
0.48043975
0.5562067
0.4437933

In [82]:
def prepare_data(seeds):
    seed_dict = seeds.set_index('Seed')['TeamID'].to_dict()
    inverted_seed_dict = {value: key for key, value in seed_dict.items()}

    return seed_dict, inverted_seed_dict

# 2025
seeds = CSV['MNCAATourneySeeds']
seeds = seeds[seeds['Season'] == SEASON]

# display(seeds)

seed_dict, inverted_seed_dict = prepare_data(seeds)

print(seed_dict)
print(inverted_seed_dict)

{'W01': 1181, 'W02': 1104, 'W03': 1458, 'W04': 1112, 'W05': 1332, 'W06': 1140, 'W07': 1388, 'W08': 1280, 'W09': 1124, 'W10': 1435, 'W11': 1433, 'W12': 1251, 'W13': 1103, 'W14': 1285, 'W15': 1352, 'W16a': 1110, 'W16b': 1291, 'X01': 1222, 'X02': 1397, 'X03': 1246, 'X04': 1345, 'X05': 1155, 'X06': 1228, 'X07': 1417, 'X08': 1211, 'X09': 1208, 'X10': 1429, 'X11a': 1400, 'X11b': 1462, 'X12': 1270, 'X13': 1219, 'X14': 1407, 'X15': 1459, 'X16': 1188, 'Y01': 1120, 'Y02': 1277, 'Y03': 1235, 'Y04': 1401, 'Y05': 1276, 'Y06': 1279, 'Y07': 1266, 'Y08': 1257, 'Y09': 1166, 'Y10': 1307, 'Y11a': 1314, 'Y11b': 1361, 'Y12': 1471, 'Y13': 1463, 'Y14': 1252, 'Y15': 1136, 'Y16a': 1106, 'Y16b': 1384, 'Z01': 1196, 'Z02': 1385, 'Z03': 1403, 'Z04': 1268, 'Z05': 1272, 'Z06': 1281, 'Z07': 1242, 'Z08': 1163, 'Z09': 1328, 'Z10': 1116, 'Z11': 1179, 'Z12': 1161, 'Z13': 1213, 'Z14': 1423, 'Z15': 1303, 'Z16': 1313}
{1181: 'W01', 1104: 'W02', 1458: 'W03', 1112: 'W04', 1332: 'W05', 1140: 'W06', 1388: 'W07', 1280: 'W08', 1124: 'W09', 1435: 'W10', 1433: 'W11', 1251: 'W12', 1103: 'W13', 1285: 'W14', 1352: 'W15', 1110: 'W16a', 1291: 'W16b', 1222: 'X01', 1397: 'X02', 1246: 'X03', 1345: 'X04', 1155: 'X05', 1228: 'X06', 1417: 'X07', 1211: 'X08', 1208: 'X09', 1429: 'X10', 1400: 'X11a', 1462: 'X11b', 1270: 'X12', 1219: 'X13', 1407: 'X14', 1459: 'X15', 1188: 'X16', 1120: 'Y01', 1277: 'Y02', 1235: 'Y03', 1401: 'Y04', 1276: 'Y05', 1279: 'Y06', 1266: 'Y07', 1257: 'Y08', 1166: 'Y09', 1307: 'Y10', 1314: 'Y11a', 1361: 'Y11b', 1471: 'Y12', 1463: 'Y13', 1252: 'Y14', 1136: 'Y15', 1106: 'Y16a', 1384: 'Y16b', 1196: 'Z01', 1385: 'Z02', 1403: 'Z03', 1268: 'Z04', 1272: 'Z05', 1281: 'Z06', 1242: 'Z07', 1163: 'Z08', 1328: 'Z09', 1116: 'Z10', 1179: 'Z11', 1161: 'Z12', 1213: 'Z13', 1423: 'Z14', 1303: 'Z15', 1313: 'Z16'}

In [85]:
def build_win_probability_matrix(label_type=LABEL_TYPE):
    win_probability_matrix = {}
    for team_id in inverted_seed_dict.keys():
        win_probability_matrix[team_id] = {}
        for opponent_id in inverted_seed_dict.keys():
            if team_id == opponent_id:
                continue
            if opponent_id in win_probability_matrix and team_id in win_probability_matrix[opponent_id]:
                win_probability_matrix[team_id][opponent_id] = 1.0 - win_probability_matrix[opponent_id][team_id]
            else:
                win_probability_matrix[team_id][opponent_id] = predict_matchup(team_id, opponent_id, season=SEASON, location=0, label_type=LABEL_TYPE)
    return win_probability_matrix

# Convert float32 values to Python float
def convert_to_serializable(obj):
    if isinstance(obj, dict):
        return {k: convert_to_serializable(v) for k, v in obj.items()}
    elif isinstance(obj, np.float32):  # Convert np.float32 to float
        return float(obj)
    return obj

def write_to_json(win_probability_matrix, filename):
    serializable_data = convert_to_serializable(win_probability_matrix)

    # Write to JSON file
    with open(filename, "w") as json_file:
        json.dump(serializable_data, json_file)
    
    print(f'{filename} written successfully!')

In [86]:
mov_matrix = build_win_probability_matrix(LabelType.MARGIN_OF_VICTORY)
write_to_json(mov_matrix, f'{SEASON}_mov_win_probability_matrix.json')

2025_mov_win_probability_matrix.json written successfully!

In [87]:
win_matrix = build_win_probability_matrix(LabelType.WIN_PROBABILITY)
write_to_json(win_matrix, f'{SEASON}_win_win_probability_matrix.json')

2025_win_win_probability_matrix.json written successfully!

In [88]:
def build_slots(season=SEASON):
    slots = CSV["MNCAATourneySlots"]
    
    slots = slots[slots['Season'] == season]

    # Select early rounds where 'Slot' does NOT start with 'R'
    play_ins = slots[~slots['Slot'].str.startswith('R')]

    # Select remaining slots where 'Slot' starts with 'R'
    actual_slots = slots[slots['Slot'].str.startswith('R')]

    # Concatenate early rounds at the top
    sorted_slots = pd.concat([play_ins, actual_slots], ignore_index=True)

    return sorted_slots

slots = build_slots()
display(slots)

    Season  Slot StrongSeed WeakSeed
0     2025   W16       W16a     W16b
1     2025   X11       X11a     X11b
2     2025   Y11       Y11a     Y11b
3     2025   Y16       Y16a     Y16b
4     2025  R1W1        W01      W16
..     ...   ...        ...      ...
62    2025  R4Y1       R3Y1     R3Y2
63    2025  R4Z1       R3Z1     R3Z2
64    2025  R5WX       R4W1     R4X1
65    2025  R5YZ       R4Y1     R4Z1
66    2025  R6CH       R5WX     R5YZ

[67 rows x 4 columns]

In [89]:
def simulate(round_slots, seeds, inverted_seeds, win_probability_matrix):
    '''
    Simulates each round of the tournament.

    Parameters:
    - round_slots: DataFrame containing information on who is playing in each round.
    - seeds (dict): Dictionary mapping seed values to team IDs.
    - inverted_seeds (dict): Dictionary mapping team IDs to seed values.
    - wins (DF): DF that includes wins prediction per matchup.
    Returns:
    - list: List with winning team IDs for each match.
    - list: List with corresponding slot names for each match.
    '''
    winners = []
    slots = []

    for slot, strong, weak in zip(round_slots.Slot, round_slots.StrongSeed, round_slots.WeakSeed):
        team_1, team_2 = seeds[strong], seeds[weak]

        team_1_prob = win_probability_matrix[team_1][team_2]

        p = np.array([team_1_prob, 1 - team_1_prob])
        p /= p.sum()  # Normalize to ensure sum is exactly 1.0

        # winner = np.random.choice([team_1, team_2], p=[team_1_prob, 1 - team_1_prob])
        winner = np.random.choice([team_1, team_2], p=p)

        # Append the winner and corresponding slot to the lists
        winners.append(winner)
        slots.append(slot)

        seeds[slot] = winner

    return [inverted_seeds[w] for w in winners], slots


def run_simulation(seeds, round_slots, win_probability_matrix, num_brackets):
    '''
    Runs a simulation of bracket tournaments.

    Parameters:
    - seeds (pd.DataFrame): DataFrame containing seed information.
    - round_slots (pd.DataFrame): DataFrame containing information about the tournament rounds.
    - wins (DF): DF that includes wins prediction per matchup.
    - brackets (int): Number of brackets to simulate.
    Returns:
    - pd.DataFrame: DataFrame with simulation results.
    '''
    # Get relevant data for the simulation
    seed_dict, inverted_seed_dict = prepare_data(seeds)
    # Lists to store simulation results
    results = []
    bracket = []
    slots = []

    # Iterate through the specified number of brackets
    for b in tqdm(range(1, num_brackets + 1)):
        # Run single simulation
        r, s = simulate(round_slots, seed_dict, inverted_seed_dict, win_probability_matrix)

        # Update results
        results.extend(r)
        bracket.extend([b] * len(r))
        slots.extend(s)

    # Create final DataFrame
    result_df = pd.DataFrame({'Bracket': bracket, 'Slot': slots, 'Team': results})

    return result_df

In [90]:
num_brackets = 100000

In [91]:
mov_result = run_simulation(seeds, slots, mov_matrix, num_brackets)
mov_result.insert(0, 'Tournament', 'M')

display(mov_result)

100%|████████████████████████████████████████████████████████████████████████| 100000/100000 [01:08<00:00, 1468.35it/s]

        Tournament  Bracket  Slot  Team
0                M        1   W16  W16a
1                M        1   X11  X11b
2                M        1   Y11  Y11a
3                M        1   Y16  Y16a
4                M        1  R1W1   W01
...            ...      ...   ...   ...
6699995          M   100000  R4Y1   Y01
6699996          M   100000  R4Z1   Z01
6699997          M   100000  R5WX   W01
6699998          M   100000  R5YZ   Y01
6699999          M   100000  R6CH   W01

[6700000 rows x 4 columns]

In [92]:
win_result = run_simulation(seeds, slots, win_matrix, num_brackets)
win_result.insert(0, 'Tournament', 'M')

display(win_result)

100%|████████████████████████████████████████████████████████████████████████| 100000/100000 [01:08<00:00, 1459.19it/s]

        Tournament  Bracket  Slot  Team
0                M        1   W16  W16b
1                M        1   X11  X11b
2                M        1   Y11  Y11b
3                M        1   Y16  Y16a
4                M        1  R1W1   W01
...            ...      ...   ...   ...
6699995          M   100000  R4Y1   Y01
6699996          M   100000  R4Z1   Z01
6699997          M   100000  R5WX   W01
6699998          M   100000  R5YZ   Z01
6699999          M   100000  R6CH   Z01

[6700000 rows x 4 columns]

In [93]:
def result_to_submission(result, filename):
    submission = result
    submission.reset_index(inplace=True, drop=True)
    submission.index.names = ['RowId']
    submission.to_csv(filename)

In [94]:
result_to_submission(mov_result, f'{SEASON}_mov_my_submission.csv')
result_to_submission(win_result, f'{SEASON}_win_my_submission.csv')